version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container thomas/src/app
    # reflect file changes from host to container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev
    # command: yarn typeorm migration:generate -n afif -d ./src/database/migrations
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: '${RDS_DB_NAME}'
      POSTGRES_USER: '${RDS_USERNAME}'
      POSTGRES_PASSWORD: '${RDS_PASSWORD}'
    ports:
      - '${RDS_PORT}:${RDS_PORT}'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

      # Connecting to the running postgres instance
      # docker ps (to figure out container id)
      # docker exec -it <container_id> bash
      # psql -U postgres
